title: "agRo-al"
author: "Alfonso Benítez-Páez"
description: "Sitio web de la Microcredencial agRo-al"
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%d, %m, %Y"

navigation:
  - {file: "README.md", title: "HOME", icon: home}

plugins:
  - jekyll-feed

template:
  name: github-pages-with-jekyll
  repo: github-pages-with-jekyll-template

theme: jekyll-theme-minima
