title: "agRo-al"
author: "Alfonso Benítez-Páez"
description: "Microcredencial para el aprendizaje sobre el manejo de datos derivados de la investigación científica"
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%d, %m, %Y"

navigation:
  - {file: "README.md", title: "HOME", icon: home}

theme: jekyll-theme-architect

remote_theme: pages-themes/architec@v0.2.0
plugins:
- jekyll-remote-theme
